name = "ai-cv-optimizer"
type = "javascript"
main = "worker.js"
compatibility_date = "2025-06-25"

[assets]
binding = "ASSETS"
directory = "dist"

[vars]
GEMINI_MODEL_NAME = "gemini-2.5-flash-preview-04-17"